version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      retries: 10
      timeout: 3s

  db.configurator:
    image: postgres:latest
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
      export PGPASSWORD=postgres;
      psql -h db -U postgres -d postgres -c \"CREATE DATABASE emergency;\"
      "
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: emergency@ciklum.com
      PGADMIN_DEFAULT_PASSWORD: emergency

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  application:
    image: emergency:latest
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy